name: notes
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

script_runner:
  scripts:
    - gen:watch: flutter pub run build_runner watch --delete-conflicting-outputs
    - gen:build: flutter pub run build_runner build --delete-conflicting-outputs
    - dev: src dev:web
    - dev:web: flutter run -d chrome
    - dev:android: flutter run -d android
    - dev:ios: flutter run -d 9EF8C0DD-B206-43E6-9205-8F0DBC214441
    - dev:macos: flutter run -d macos
    - dev:linux: flutter run -d linux
    - dev:windows: flutter run -d windows
    - build:web: flutter build web --release
    - build:android: flutter build apk --split-per-abi
    - build:ios: flutter build ios --release --no-codesign
    - build:macos: flutter build macos --release
    - build:linux: flutter build linux --release
    - build:windows: flutter build windows --release
    - build:all: scr build:web && scr build:android && scr build:ios && scr build:macos && scr build:linux && scr build:windows
    - lint:fix: dart fix --apply
    - lint: dart analyze --fatal-infos --fatal-warnings .
    - test: flutter test --coverage

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  # core
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  chopper: ^6.1.1
  go_router: ^6.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  i18n_extension: ^7.0.0
  flutter_secure_storage: ^8.0.0 ## for sensitive data storage (like jwt token)
  flutter_platform_widgets: ^3.0.0
  flutter_dotenv: ^5.0.2

  # ui
  carousel_slider: ^4.2.1
  badges: ^3.0.2
  quickalert: ^1.0.1
  auto_size_text: ^3.0.0
  formz: ^0.4.1
  google_fonts: ^4.0.3
  responsive_framework: ^0.2.0

  # behavious
  firebase_messaging: ^14.2.4
  url_launcher: ^6.1.9
  file_picker: ^5.2.5
  socket_io_client: ^2.0.1
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  # core
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  chopper_generator: ^6.0.0
  import_sorter: ^4.6.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - .env
